import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import Nav from "./components/nav";
import Media from "./components/media";
const inter = Fira_Code({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid grid-cols-12">
          <div className="col-span-2">
            <Media />{" "}
          </div>
          <div className="col-span-8">
            <Nav />
            {children}
          </div>
          <div className="col-span-2"></div>
        </div>
      </body>
    </html>
  );
}
